trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: 2.1.505

steps:
- task: UseDotNet@2
  displayName: "Use .Net Core SDK $(dotnetSdkVersion)"
  inputs:
    packageType: "sdk"
    version: "$(dotnetSdkVersion)"

- task: Npm@1
  displayName: "Run npm install"
  inputs:
    verbose: false

- script: "./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)"
  displayName: Compile Sass assets

- task: gulp@1
  displayName: Run gulp tasks

- script: 'echo $(Build.DefinitionName), $(Build.BuildId), $(Build.BUildNumber) > buildinfo.txt'
  displayName: 'Write build info to buildinfo.txt'
  workingDirectory: $(wwwrootDir)

#restore
- task: DotNetCoreCLI@2
  displayName: "Restore the project"
  inputs:
    command: restore
    projects: '**/*.csproj'

#build
- task: DotNetCoreCLI@2
  displayName: "Build the project - $(buildConfiguration)"
  inputs:
    command: build
    arguments: "--no-restore --configuration $(buildConfiguration)"
    projects: '**/*.csproj'

#publish
- task: DotNetCoreCLI@2
  displayName: "Publish the project - $(buildConfiguration)"
  inputs:
    command: publish
    arguments: "--no-build --configuration $(buildConfiguration)"
    projects: '**/*.csproj'
    publishWebProjects: false
    zipAfterPublish: true

#drop to artifacts
- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: succeeded()
